swagger: '2.0'
info:
  description: SCIM 2.0 endpoints
  version: '1.0'
  title: SCIM 2.0 Endpoint Swagger Definition
  contact:
    name: WSO2 Identity Server Team
    url: 'http://wso2.com'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
basePath: /scim2/
paths:
  /scim2/Me:
    get:
      tags:
        - Me Endpoint
      summary: Return the authenticated user.
      description: Returns HTTP 200 if the user is found.
      operationId: getUserMe
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
      responses:
        '200':
          description: Valid user is found
        '404':
          description: Valid user is not found
    post:
      tags:
        - Me Endpoint
      summary: Return the user which was anonymously created
      description: Returns HTTP 201 if the user is successfully created.
      operationId: createUserMe
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '201':
          description: Valid user is created
        '404':
          description: Valid user is not found
    put:
      tags:
        - Me Endpoint
      summary: Return the updated user
      description: Returns HTTP 404 if the user is not found.
      operationId: updateUserMe
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: User is updated
        '404':
          description: Valid user is not found
    delete:
      tags:
        - Me Endpoint
      summary: Delete the authenticated user.
      description: Returns HTTP 204 if the user is successfully deleted.
      operationId: deleteUserMe
      produces:
        - application/json
        - application/scim+json
      parameters: []
      responses:
        '204':
          description: User is deleted
        '404':
          description: Valid user is not found
    patch:
      tags:
        - Me Endpoint
      summary: Return the updated user
      description: Returns HTTP 404 if the user is not found.
      operationId: patchUserMe
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: User is updated
        '404':
          description: Valid user is not found
  /scim2/Groups:
    get:
      tags:
        - Groups Endpoint
      summary: 'Return groups according to the filter, sort and pagination parameters'
      description: Returns HTTP 404 if the groups are not found.
      operationId: getGroup
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - name: filter
          in: query
          description: Filter expression for filtering
          required: false
          type: string
        - name: startIndex
          in: query
          description: The 1-based index of the first query result
          required: false
          type: integer
          format: int32
        - name: count
          in: query
          description: Specifies the desired maximum number of query results per page.
          required: false
          type: integer
          format: int32
        - name: sortBy
          in: query
          description: |-
            Specifies the attribute whose value
            SHALL be used to order the returned responses
          required: false
          type: string
        - name: sortOder
          in: query
          description: The order in which the "sortBy" parameter is applied.
          required: false
          type: string
        - name: domain
          in: query
          description: The name of the user store where filtering needs to be applied.
          required: false
          type: string
      responses:
        '200':
          description: Valid groups are found
        '404':
          description: Valid groups are not found
    post:
      tags:
        - Groups Endpoint
      summary: Return the group which was created
      description: Returns HTTP 201 if the group is successfully created.
      operationId: createGroup
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '201':
          description: Valid group is created
        '404':
          description: Group is not found
  /scim2/Groups/.search:
    post:
      tags:
        - Groups Endpoint
      summary: 'Return groups according to the filter, sort and pagination parameters'
      description: Returns HTTP 404 if the groups are not found.
      operationId: getGroupsByPost
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Valid groups are found
        '404':
          description: Valid groups are not found
  '/scim2/Groups/{id}':
    get:
      tags:
        - Groups Endpoint
      summary: Return the group with the given id
      description: Returns HTTP 200 if the group is found.
      operationId: getGroup by id
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: id
          in: path
          description: Unique id of the resource type.
          required: true
          type: string
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
      responses:
        '200':
          description: Valid group is found
        '404':
          description: Valid group is not found
    put:
      tags:
        - Groups Endpoint
      summary: Return the updated group
      description: Returns HTTP 404 if the group is not found.
      operationId: updateGroup
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: id
          in: path
          description: Unique id of the resource type.
          required: true
          type: string
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Group is updated
        '404':
          description: Valid group is not found
    delete:
      tags:
        - Groups Endpoint
      summary: Delete the group with the given id
      description: Returns HTTP 204 if the group is successfully deleted.
      operationId: deleteGroup
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: id
          in: path
          description: Unique id of the resource type.
          required: true
          type: string
      responses:
        '204':
          description: Group is deleted
        '404':
          description: Valid group is not found
    patch:
      tags: 
        - Groups Endpoint
      summary: Return the updated group
      description: Returns HTTP 404 if the group is not found.
      operationId: patchGroup
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: id
          in: path
          description: Unique id of the resource type.
          required: true
          type: string
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Group is updated
        '404':
          description: Valid group is not found
  /scim2/Users:
    get:
      tags:
        - Users Endpoint
      summary: 'Return users according to the filter, sort and pagination parameters'
      description: Returns HTTP 404 if the users are not found.
      operationId: getUser
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - name: filter
          in: query
          description: Filter expression for filtering
          required: false
          type: string
        - name: startIndex
          in: query
          description: The 1-based index of the first query result
          required: false
          type: integer
          format: int32
        - name: count
          in: query
          description: Specifies the desired maximum number of query results per page.
          required: false
          type: integer
          format: int32
        - name: sortBy
          in: query
          description: |-
            Specifies the attribute whose value
            SHALL be used to order the returned responses
          required: false
          type: string
        - name: sortOder
          in: query
          description: The order in which the "sortBy" parameter is applied.
          required: false
          type: string
        - name: domain
          in: query
          description: The name of the user store where filtering needs to be applied.
          required: false
          type: string
      responses:
        '200':
          description: Valid users are found
        '404':
          description: Valid users are not found
    post:
      tags:
        - Users Endpoint
      summary: Return the user which was created
      description: Returns HTTP 201 if the user is successfully created.
      operationId: createUser
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '201':
          description: Valid user is created
        '404':
          description: Valid user is not found
  /scim2/Users/.search:
    post:
      tags:
        - Users Endpoint
      summary: 'Return users according to the filter, sort and pagination parameters'
      description: Returns HTTP 404 if the users are not found.
      operationId: getUsersByPost
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Valid users are found
        '404':
          description: Valid users are not found
  '/scim2/Users/{id}':
    get:
      tags:
        - Users Endpoint
      summary: Return the user with the given id
      description: Returns HTTP 200 if the user is found.
      operationId: getUser by id
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: id
          in: path
          description: Unique id of the resource type.
          required: true
          type: string
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
      responses:
        '200':
          description: Valid user is found
        '404':
          description: Valid user is not found
    put:
      tags:
        - Users Endpoint
      summary: Return the updated user
      description: Returns HTTP 404 if the user is not found.
      operationId: updateUser
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: id
          in: path
          description: Unique id of the resource type.
          required: true
          type: string
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: User is updated
        '404':
          description: Valid user is not found
    delete:
      tags:
        - Users Endpoint
      summary: Delete the user with the given id
      description: Returns HTTP 204 if the user is successfully deleted.
      operationId: deleteUser
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: id
          in: path
          description: Unique id of the resource type.
          required: true
          type: string
      responses:
        '204':
          description: User is deleted
        '404':
          description: Valid user is not found
    patch:
      tags:
        - Users Endpoint
      summary: Return the updated user
      description: Return HTTP 404 if the user is not found.
      operationId: patchUser
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - name: id
          in: path
          description: Unique id of the resource type.
          required: true
          type: string
        - name: attributes
          in: query
          description: SCIM defined attributes parameter.
          required: false
          type: string
        - name: excludedAttributes
          in: query
          description: SCIM defined excludedAttribute parameter.
          required: false
          type: string
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: User is updated
        '404':
          description: Valid user is not found
  /scim2/Bulk:
    post:
      tags:
        - Bulk Endpoint
      summary: Return the bulk response depends.
      description: Returns HTTP 201 if the users are successfully created.
      operationId: createBulkUsers
      consumes:
        - application/scim+json
      produces:
        - application/json
        - application/scim+json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '201':
          description: Valid user is created
        '404':
          description: Valid user is not found
  
  /scim2/ResourceType:
    get:
      tags:
        - ResourceType Endpoint
      summary: Return the ResourceType schema.
      description: Returns HTTP 200 if the schema is found.
      operationId: getResourceType
      produces:
        - application/json
        - application/scim+json
      parameters: []
      responses:
        '200':
          description: Schema is found
        '404':
          description: Schema is not found
  /scim2/ServiceProviderConfig:
    get:
      tags:
        - ServiceProviderConfig Endpoint
      summary: Return the ServiceProviderConfig schema.
      description: Returns HTTP 200 if the schema is found.
      operationId: getServiceProviderConfig
      produces:
        - application/json
        - application/scim+json
      parameters: []
      responses:
        '200':
          description: Schema is found
        '404':
          description: Schema is not found
